SamsWarehouseWebApp/Controllers/ItemController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SamsWarehouseWebApp.Models.Data;
using SamsWarehouseWebApp.Models.DBContext;
using SamsWarehouseWebApp.Models.DTO;
using SamsWarehouseWebApp.Services;
using System.Data;
using System.Linq;

namespace SamsWarehouseWebApp.Controllers
{
    public class ItemController : Controller
    {
        private readonly ItemDBContext _itemConext;
        private readonly SanitiserService _sanitiserService;

        public ItemController(ItemDBContext itemConext, SanitiserService sanitiserService)
        {
            _itemConext = itemConext;
            _sanitiserService = sanitiserService;
        }
        /// <summary>
        /// Returns an index view of items page
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View(_itemConext.Items.AsEnumerable());
        }
        /// <summary>
        /// HTTP GET request that retrieves and displays items in a partial view (item table)
        /// </summary>
        /// <param name="query"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult> ItemTablePartial(string query = "")
        {
            string SanQuery = _sanitiserService.Sanitiser.Sanitize(query);
            // Query string is filtered
            if (!string.IsNullOrEmpty(SanQuery))
            {
                // Item data is filtered based on item name and unit using string query
                var filteredItemData = _itemConext.Items.Where(c => c.ItemName.Contains(query) || c.Unit.Contains(query)).AsEnumerable();
                // Partial chunk of html is retrieved to display the filtered item in the item table
                return PartialView("_ItemTable", filteredItemData);
            }
            
            Thread.Sleep(2000);
            var itemData = _itemConext.Items.AsEnumerable();

            // Item data displayed in the item table 
            return PartialView("_ItemTable", itemData);
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create()
        {
            Thread.Sleep(2000);
            return PartialView("_CreateItem");
        }

        // POST: ItemController/
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<ActionResult> Create([FromBody] ItemCreateDTO itemCreate)
        {
            try
            {
                var test = HttpContext.Request;
                Thread.Sleep(2000);
                // simple error handling
                if (ModelState.IsValid)
                {

                    Item item = new Item
                    {
                        ItemId = itemCreate.ItemId,
                        ItemName = itemCreate.ItemName,
                        Unit = itemCreate.Unit,
                        UnitPrice = itemCreate.UnitPrice
                    };

                    _itemConext.Items.Add(item);
                    await _itemConext.SaveChangesAsync();
                    return Created("/Item/Create", item);
                }
                else
                {
                    return BadRequest("There was an issue processing the provided model");
                }
            }
            catch
            {
                return Problem("There was an issue processing your request");
            }
        }

        /// <summary>
        /// HTTP GET method that retrieves item data by id. 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: ItemController/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            //Thread.Sleep(2000);
            if (id == 0)
            {
                return RedirectToAction(nameof(Index));
            }

            var item = _itemConext.Items.FirstOrDefault(c => c.ItemId == id);

            return item != null ? PartialView("_Edit",item) : RedirectToAction(nameof(Index));
        }
        /// <summary>
        /// HTTP PUT method for editing an item 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="item"></param>
        /// <returns></returns>
        // PUT: ItemController/Edit/5
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        [HttpPut]
        public async Task<ActionResult> Edit([FromQuery] int id, [FromBody] Item item)
        {
            //if (id != item.ItemId)
            //{
            //    return NotFound();
            //}
            item.ItemId = id;
            if (ModelState.IsValid)
            {
                _itemConext.Items.Update(item);
                await _itemConext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }
        /// <summary>
        /// HTTP POST method that is used to delete items from a list. Retrieves item by id from the database using the _dbitemContext.
        /// If the item is retrieved, delete it from the list and save changes. Redirect to item index page. 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: ItemController/Delete/5
        [HttpDelete]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete([FromQuery] int id)
        {
            try
            {
                var item = _itemConext.Items.FirstOrDefault(c => c.ItemId == id);
                if (item != null)
                {
                    _itemConext.Items.Remove(item);
                    await _itemConext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

SamsWarehouseWebApp/Controllers/ListController.cs
using Ganss.Xss;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SamsWarehouseWebApp.Models.Data;
using SamsWarehouseWebApp.Models.DBContext;
using SamsWarehouseWebApp.Repository;
using SamsWarehouseWebApp.Services;
using System.Security.Claims;
using TypicalTools.Models;

namespace SamsWarehouseWebApp.Controllers
{
    public class ListController : Controller
    {
        private readonly ItemDBContext _dbcontext;
        private readonly SanitiserService _sanitiserService;
        //private readonly Microsoft.AspNetCore.Identity.UserManager<AppUser> _userManager;

        public ListController(ItemDBContext dbcontext, SanitiserService sanitiserService) /*Microsoft.AspNetCore.Identity.UserManager<AppUser> userManager*/
        {
            _dbcontext = dbcontext; 
            _sanitiserService = sanitiserService;
            //_userManager = userManager;
        }
        /// <summary>
        /// Index controller method that displays Shopping Lists page
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            //if (string.IsNullOrWhiteSpace(HttpContext.Session.GetString("ID")))
            //{
            //    return RedirectToAction("Login", "Home");
            //}

            //AppUser user = await _userManager.GetUserAsync(User);
            ViewBag.UserId = HttpContext.Session.GetString("ID");


            return View();
        }
        /// <summary>
        /// Creates and displays a drop-down list for all user lists. First the method checks the user's ID to authorise the user to use the
        /// drop-down list. The user's ID is then used to display all lists created by that user. If no lists have been made for that user, "No entries" 
        /// will be displayed in the drop-down list. When a list option is selected in the DDL, a partial view is returned to display the list's items. 
        /// </summary>
        /// <returns></returns>
        //[Authorize(Roles = "Admin")]
        //public async Task<IActionResult> ShoppingListDDL()
        //{
        //    //AppUser user = await _userManager.GetUserAsync(User);
        //    var userId = HttpContext.User.Claims.Where(c => c.Type == "Id").FirstOrDefault();


        //    if (userId == null)
        //    {
        //        return Unauthorized();
        //    }

        //    //string userId = HttpContext.Session.GetString("ID");

        //    var user = _dbcontext.Users.Where(c => c.UserId == int.Parse(userId))
        //                            .Include(c => c.Lists).FirstOrDefault();

        //    if (user == null)
        //    {
        //        return BadRequest();
        //    }

        //    var selectList = user.Lists.Select(c => new SelectListItem
        //    {
        //        Text = c.ListName,
        //        Value = c.ListId.ToString()
        //    }).ToList();

        //    if (selectList.Count == 0)
        //    {
        //        selectList.Add(new SelectListItem
        //        {
        //            Text = "No Entries",
        //            Value = "0"
        //        });
        //    }

        //    ViewBag.SelectList = selectList;

        //    return PartialView("_ListDDL");
        //}

        [Authorize(Roles = "StandardUser")]
        public async Task<IActionResult> ShoppingListDDL()
            {
            var userId = HttpContext.User.Claims.Where(c => c.Type == ClaimTypes.Sid).FirstOrDefault()?.Value;

            //int userId = Int32.Parse(HttpContext.User.Claims.Where(a => a.Type == ClaimTypes.Sid).Select(a => a.Value).SingleOrDefault());

            if (!int.TryParse(userId,out int userid))
            {
                return Unauthorized();
            }

            var ddl = _dbcontext.Lists.Where(c => c.UserId == userid).ToList();
            var selectlist = ddl.Select(c => new SelectListItem
            {
                Text = c.ListName,
                Value = c.ListId.ToString()
            }).ToList();
            ViewBag.List = selectlist;
            return PartialView("_ListDDL");

        }

        /// <summary>
        /// Add New List for user. Retrieves ID from session and checks if user is authorised to create a new list. 
        /// </summary>
        /// <param name="listName"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> AddNewList([FromBody] string listName, IFormCollection collection)
        {
            var content = _sanitiserService.Sanitiser.Sanitize(collection["Content"]);

            // retrieve ID from session
            string id = HttpContext?.Session?.GetString("ID");

            var sanitizer = new HtmlSanitizer();

            string userInput = "<p>This is <b>some</b> <script>alert('dangerous script!');</script> HTML input.</p>";
            string sanitizedHtml = sanitizer.Sanitize(userInput);

            //HtmlSanitizer sanitizer = new HtmlSanitizer();
            //sanitizer.AllowedAttributes.Add("class");

            //var content = sanitizer.Sanitize(listName);

            //var content = collection["Content"];

            //string query = "SELECT * FROM Entries WHERE Type='Sanitised' AND Content LIKE '" + content + "'";

            //var enteredListName = _dbcontext.Lists.FromSqlRaw(query).ToList();

            if (!int.TryParse(id, out int userID))
            {
                return Unauthorized();
            }

            if (_dbcontext.Lists.Any(c => c.ListName == listName && c.UserId == userID))
            {
                return BadRequest();
            }

            List newList = new List()
            {
                ListName = listName,
                UserId = userID
            };
            _dbcontext.Lists.Add(newList);
            _dbcontext.SaveChanges();

            return Ok();
        }
        /// <summary>
        /// Retrieves all items for a user's selected list 
        /// </summary>
        /// <param name="listID"></param>
        /// <returns></returns>
        public async Task<IActionResult> GetItemsForList([FromQuery] int listID)
        {
            var date = _dbcontext.Lists.Where (c => c.ListId == listID).FirstOrDefault().Created;
            ViewBag.CreatedDate = date;
            List<ListItems> items = _dbcontext.ListItems.Include(c => c.Item)
                                                                 .Where(c => c.ListId == listID).ToList();
            //.Select(c => c.Item)
            //.ToList();



            return PartialView("_ItemsForListPartial", items);
        }

        /// <summary>
        /// Removes an item from the selected user list
        /// </summary>
        /// <param name="item"></param>
        /// <returns></returns>
        [HttpDelete]
        public async Task<IActionResult> RemoveItemFromList([FromBody] ListItems item)
        {
            var listItem = _dbcontext.ListItems.Where(c => c.ListId == item.ListId && c.ItemId == item.ItemId)
                                                         .FirstOrDefault();
            try
            {
                if (listItem != null)
                {
                    _dbcontext.ListItems.Remove(listItem);
                    _dbcontext.SaveChanges();
                    return Ok();
                }
                return BadRequest();
            }

            catch (Exception e)
            {

                throw;
            }
        }


        /// <summary>
        /// Adds Item To a Shopping List
        /// </summary>
        /// <param name="item"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> AddItemToList([FromBody] ListItems item)
        {
            try
            {
                if (_dbcontext.ListItems.Any(c => c.ListId == item.ListId && c.ItemId == item.ItemId && c.Quantity == item.Quantity))
                {
                    return BadRequest();
                }

                _dbcontext.ListItems.Add(item);
                _dbcontext.SaveChanges();
                return Ok();
            }
            catch (Exception e)
            {
                return Problem();
            }
        }
        /// <summary>
        /// List controller method used to delete a user's selected shopping list 
        /// </summary>
        /// <param name="listId"></param>
        /// <returns></returns>
        [HttpDelete]
        public async Task<ActionResult> DeleteShoppingList([FromBody] int listID)
        {
            if (listID != null)
            {
                var listToDelete = _dbcontext.Lists.Where(c => c.ListId == listID).FirstOrDefault();
                _dbcontext.Lists.Remove(listToDelete);
                _dbcontext.SaveChanges();

                return Ok();
            }
            return BadRequest();
        }
    }
}

SamsWarehouseWebApp/Views/Shared/_Layout.cshtml
@{
    string? theme = Context?.Session.GetString("theme");
    bool isLoggedIn = User?.Identity?.IsAuthenticated ?? false;
    bool isAdmin = User?.IsInRole("Admin") ?? false;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SamsWarehouseWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SamsWarehouseWebApp.styles.css" asp-append-version="true" />
@*    <link rel="stylesheet" href="~/css/LightTheme.css" id="themeStyle" />
*@

    @if (Context.Request.Cookies.Any(a => a.Key == "theme"))
    {
        if (Context?.Request?.Cookies?["theme"].ToString() == "dark")
        {
            <link rel="stylesheet" href="~/css/DarkTheme.css" id="themeStyle" />
        }
        else
        {
            <link rel="stylesheet" href="~/css/LightTheme.css" id="themeStyle" />
        }
    }
    else
    {
        <link rel="stylesheet" href="~/css/LightTheme.css" id="themeStyle" />

    }

</head>
<body style="background-color: var(--colour-0); color: var(--text-colour) !important" >
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3" style="background-color: var(--colour-1)">
            <img src="/Elements/Sams Warehouse Shopping Cart.svg" height="75" width="75" class="me-1" id="cartIcon" />
            <div class="container-fluid">
                <a class="navbar-brand" style="color: white" asp-area="" asp-controller="Home" asp-action="AboutUs">Sams Warehouse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" style="color: white !important" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: white !important" asp-area="" asp-controller="Item" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: white !important" asp-area="" asp-controller="List" asp-action="Index">Shopping Lists</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: white !important" asp-area="" asp-controller="Encryption" asp-action="Index">Image Gallery</a>
                        </li>
                    </ul>

                    @if (isLoggedIn)
                    {
                        <div class="me-3" style="color: white">@*@User.FindFirst("Email").Value*@</div>
                        <a asp-controller="Home" asp-action="Logout" class="btn btn-warning me-3 white-text">Logout</a>
                    }
                    else
                    {
                        <a asp-controller="Home" asp-action="Login" class="btn btn-success me-3 white-text">Login</a>
                        <a asp-controller="Home" asp-action="Register" class="btn btn-warning me-3">Register</a>
                    }
                    <input type="button" value="Switch Theme" class="btn btn-primary" id="btnSwitchTheme" onclick="switchTheme()" />

                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SamsWarehouseWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>

        function switchTheme()
        {
            let themeCurrent = localStorage.getItem("theme");

            if(themeCurrent && themeCurrent == "dark")
            {
                localStorage.setItem("theme","light");
                document.cookie = "theme=lght;path=/";
                document.getElementById("themeStyle").setAttribute("href","/css/LightTheme.css")
            }
            else
            {
                localStorage.setItem("theme","dark");
                document.cookie = "theme=dark;path=/";
                document.getElementById("themeStyle").setAttribute("href","/css/DarkTheme.css")
            }
        }

        let cartIcon = document.getElementById('cartIcon');
        cartIcon.addEventListener('mouseenter', startSpin)
        cartIcon.addEventListener('mouseleave', stopSpin)

        let spinningIcons = document.getElementsByClassName('material-icons');

        for (index in spinningIcons) {
            spinningIcons[index].addEventListener('mouseenter', startSpin)
            spinningIcons[index].addEventListener('mouseleave', stopSpin)
        }

        function startSpin(e) {
            let element = e.target;
            element.classList.add("rotateAnimation")
        }

        function stopSpin(e) {
            let element = e.target;
            element.classList.remove("rotateAnimation")
        }
    </script>

</body>
</html>